import {
  CommandPaletteContainer,
  CommandInputWrapper,
  CommandInput,
  ResultList,
  ResultHeader,
  ResultTitle,
  ResultCount,
  CustomTabsContainer,
  CustomTabButton,
  TaskItemContainer,
  StyledBadge,
  StyledCategory,
  RadioCircle,
  CheckSquare,
  PaletteFooter,
  AddTaskButton,
  ItemText,
  CollapsedSearchContainer,
} from '../../../../Workspace.styles';

export {
  CommandPaletteContainer,
  CommandInputWrapper,
  CommandInput,
  ResultList,
  ResultHeader,
  ResultTitle,
  ResultCount,
  CustomTabsContainer,
  CustomTabButton,
  TaskItemContainer,
  StyledBadge,
  StyledCategory,
  RadioCircle,
  CheckSquare,
  PaletteFooter,
  AddTaskButton,
  ItemText,
  CollapsedSearchContainer,
};
